version: '3.9'

services:
  console:
    image: prepared-interview-console:latest
    build:
      context: .
      dockerfile: Dockerfile
      target: build
    command: ['yarn', 'start']
    ports:
      - '3002:3002'
    environment:
      MEDIA_CDN_URL: 'dev.cdn.preparedapp.com'
